import "./globals.css";
import { Poppins } from "next/font/google";
import Header from "../app/components/header/header";
import Footer from "../app/components/footer/footer";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Header />

        <main>{children}</main>
      </body>
      <Footer />
    </html>
  );
}
